import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentGroup } from "@/lib/group";
import { HelpButton } from "@/components/HelpButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const group = await getCurrentGroup();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 모바일 브라우저에서 h-full(=100%)은 주소창이 접히기 전 최대 높이 기준으로
          계산되는 경우가 있어, 실제 화면보다 콘텐츠가 길어져도 스크롤로 빠져나갈
          방법이 없어지는 문제가 있었다. 실시간 뷰포트를 따라가는 dvh로 교체. */}
      <body className="flex h-dvh flex-col">
        {children}
        {group && <HelpButton />}
      </body>
    </html>
  );
}
